# Generated by Django 6.0.2 on 2026-02-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datamining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datamining_code', models.CharField(max_length=120)),
                ('pig_age_days', models.CharField(max_length=120)),
                ('avg_weight', models.CharField(max_length=120)),
                ('feed_quantity', models.CharField(max_length=120)),
                ('number_of_feeding_per_day', models.IntegerField()),
                ('feeding_interval', models.IntegerField()),
                ('pen_capacity', models.FloatField()),
                ('pen_status', models.CharField(max_length=120)),
                ('growth_stage', models.CharField(max_length=120)),
                ('feed_type', models.CharField(max_length=120)),
                ('device_code', models.CharField(max_length=120)),
                ('repeat_days', models.CharField(max_length=120)),
                ('notes', models.DateTimeField()),
            ],
        ),
    ]
