"""
Django settings for smarthogserver project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from importlib.util import find_spec
from pathlib import Path
from urllib.parse import parse_qs, urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-%66a51-3x78bu!hk-5i92%vwei6o61#o-k62(gs$3f3y^zsb)c",
)
SECRET_KEY_FALLBACKS = [
    key.strip()
    for key in os.environ.get("DJANGO_SECRET_KEY_FALLBACKS", "").split(",")
    if key.strip()
]

# SECURITY WARNING: don't run with debug turned on in production!
running_on_render = os.environ.get("RENDER", "").strip().lower() == "true"
DEBUG = os.environ.get("DJANGO_DEBUG", "False" if running_on_render else "True").lower() == "true"

allowed_hosts_raw = os.environ.get(
    "DJANGO_ALLOWED_HOSTS",
    "localhost,127.0.0.1",
)
ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_raw.split(",") if host.strip()]

render_external_hostname = os.environ.get("RENDER_EXTERNAL_HOSTNAME", "").strip()
if render_external_hostname and render_external_hostname not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(render_external_hostname)

CSRF_TRUSTED_ORIGINS = []
render_external_url = os.environ.get("RENDER_EXTERNAL_URL", "").strip()
if render_external_url.startswith("https://"):
    CSRF_TRUSTED_ORIGINS.append(render_external_url)


# Application definition

HAS_CORSHEADERS = find_spec('corsheaders') is not None

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'auth.apps.AuthConfig',
    'dashboard.apps.DashboardConfig',
    'pen',
    'batch',
    'growth',
    'device',
    'feeding',
    'record',
    'datamining',
    'reports.apps.ReportsConfig',
]

if HAS_CORSHEADERS:
    INSTALLED_APPS.insert(0, 'corsheaders')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if HAS_CORSHEADERS:
    MIDDLEWARE.insert(0, 'corsheaders.middleware.CorsMiddleware')

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_HEADERS = [
    "content-type",
    "authorization",
    "x-csrftoken",
]


ROOT_URLCONF = 'smarthogserver.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'smarthogserver.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

def _database_config():
    database_url = os.environ.get("DATABASE_URL", "").strip()
    conn_max_age = int(os.environ.get("DJANGO_DB_CONN_MAX_AGE", "600"))
    default_sslmode = "require" if running_on_render else "prefer"

    if database_url:
        parsed = urlparse(database_url)
        query_params = parse_qs(parsed.query)
        sslmode = (
            os.environ.get("DJANGO_DB_SSLMODE", "").strip()
            or (query_params.get("sslmode", [None])[0] or default_sslmode)
        )

        config = {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": parsed.path.lstrip("/"),
            "USER": parsed.username or "",
            "PASSWORD": parsed.password or "",
            "HOST": parsed.hostname or "",
            "PORT": str(parsed.port or 5432),
            "CONN_MAX_AGE": conn_max_age,
        }

        if sslmode:
            config["OPTIONS"] = {"sslmode": sslmode}

        return config

    db_name = os.environ.get("DB_NAME", "").strip()
    db_user = os.environ.get("DB_USER", "").strip()
    db_password = os.environ.get("DB_PASSWORD", "").strip()
    db_host = os.environ.get("DB_HOST", "").strip()
    db_port = os.environ.get("DB_PORT", "5432").strip()
    db_engine = os.environ.get("DB_ENGINE", "django.db.backends.postgresql").strip()

    if all([db_name, db_user, db_password, db_host, db_port]):
        config = {
            "ENGINE": db_engine,
            "NAME": db_name,
            "USER": db_user,
            "PASSWORD": db_password,
            "HOST": db_host,
            "PORT": db_port,
            "CONN_MAX_AGE": conn_max_age,
        }
        sslmode = os.environ.get("DJANGO_DB_SSLMODE", default_sslmode).strip()
        if sslmode:
            config["OPTIONS"] = {"sslmode": sslmode}
        return config

    return {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }


DATABASES = {
    "default": _database_config(),
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
