# Generated by Django 6.0.2 on 2026-02-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PigBatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=120)),
                ('batch_name', models.CharField(max_length=120)),
                ('no_of_pigs', models.IntegerField()),
                ('current_age', models.IntegerField()),
                ('avg_weight', models.FloatField()),
                ('notes', models.CharField(max_length=120)),
                ('pen_code', models.CharField(max_length=120)),
                ('growth', models.CharField(max_length=120)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
