# Generated by Django 6.0.2 on 2026-02-23 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0001_initial'),
        ('pen', '0003_alter_pen_pen_code_alter_pen_pen_name'),
        ('batch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pigbatches',
            name='growth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='growth.growthstage'),
        ),
        migrations.AlterField(
            model_name='pigbatches',
            name='pen_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='pen.pen'),
        ),
    ]
