# Generated by Django 6.0.2 on 2026-02-23 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0002_alter_pigbatches_growth_stage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pigbatches',
            old_name='growth',
            new_name='growth_stage',
        ),
        migrations.AlterField(
            model_name='pigbatches',
            name='growth_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='growth.growthstage'),
        ),
        migrations.AlterField(
            model_name='pigbatches',
            name='pen_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='pen.pen'),
        ),
    ]
