# Generated by Django 6.0.2 on 2026-02-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0003_rename_growth_pigbatches_growth_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pigbatches',
            name='batch_code',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='pigbatches',
            name='batch_name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
