# Generated by Django 6.0.2 on 2026-02-23 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pen', '0003_alter_pen_pen_code_alter_pen_pen_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_code', models.CharField(max_length=120, unique=True)),
                ('device_type', models.CharField(max_length=120)),
                ('date', models.DateTimeField()),
                ('pen_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='pen.pen')),
            ],
        ),
    ]
