# Generated by Django 6.0.2 on 2026-02-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pen_code', models.CharField(max_length=120)),
                ('pen_name', models.CharField(max_length=120)),
                ('capacity', models.CharField(max_length=120)),
                ('status', models.CharField(max_length=120)),
                ('notes', models.CharField(max_length=120)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
