# Generated by Django 6.0.2 on 2026-02-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pen',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pen',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('occupied', 'Occupied')], default='available', max_length=120),
        ),
    ]
