# Generated by Django 6.0.2 on 2026-02-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0002_alter_pen_capacity_alter_pen_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pen',
            name='pen_code',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='pen',
            name='pen_name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
