# Generated by Django 6.0.2 on 2026-02-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('growth_code', models.CharField(max_length=120)),
                ('growth_name', models.CharField(max_length=120)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
