# Generated by Django 6.0.2 on 2026-02-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growthstage',
            name='growth_code',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='growthstage',
            name='growth_name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
