CREATE TABLE IF NOT EXISTS datamining_pigmldata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_code VARCHAR(120) NOT NULL UNIQUE,
    batch_code VARCHAR(120) NOT NULL,
    pen_code VARCHAR(120) NOT NULL,
    sample_date TIMESTAMPTZ NOT NULL,
    pig_age_days INTEGER NOT NULL CHECK (pig_age_days BETWEEN 30 AND 150),
    avg_weight DOUBLE PRECISION NOT NULL,
    total_feed_quantity DOUBLE PRECISION NOT NULL,
    feeding_count INTEGER NOT NULL CHECK (feeding_count BETWEEN 2 AND 5),
    avg_feeding_interval_hours DOUBLE PRECISION NOT NULL,
    pen_capacity INTEGER NOT NULL CHECK (pen_capacity BETWEEN 10 AND 30),
    pen_status VARCHAR(120) NOT NULL CHECK (pen_status IN ('available', 'occupied')),
    growth_stage VARCHAR(120) NOT NULL CHECK (growth_stage IN ('HOGPRE', 'STARTER', 'GROWER', 'FINISHER')),
    feed_type_mode VARCHAR(20) NOT NULL CHECK (feed_type_mode IN ('manual', 'automatic')),
    device_code VARCHAR(120) NOT NULL,
    window_days INTEGER NOT NULL CHECK (window_days IN (1, 7)),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    record_id BIGINT NOT NULL UNIQUE REFERENCES record_record(id)
);

CREATE INDEX IF NOT EXISTS idx_datamining_pigmldata_batch_code
    ON datamining_pigmldata (batch_code);

CREATE INDEX IF NOT EXISTS idx_datamining_pigmldata_sample_date
    ON datamining_pigmldata (sample_date);

CREATE INDEX IF NOT EXISTS idx_datamining_pigmldata_growth_stage
    ON datamining_pigmldata (growth_stage);
