# Generated by Django 6.0.2 on 2026-02-23 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batch', '0004_alter_pigbatches_batch_code_and_more'),
        ('device', '0001_initial'),
        ('pen', '0003_alter_pen_pen_code_alter_pen_pen_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_code', models.CharField(max_length=120, unique=True)),
                ('feed_quantity', models.FloatField()),
                ('feed_time', models.DateTimeField()),
                ('feed_type', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('batch_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batch.pigbatches')),
                ('device_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.device')),
                ('pen_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pen.pen')),
            ],
        ),
    ]
