# Generated by Django 6.0.2 on 2026-03-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeding',
            name='repeat_days',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
