# Generated by Django 6.0.2 on 2026-03-18 00:00

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def set_default_growth_stage(apps, schema_editor):
    GrowthStage = apps.get_model('growth', 'GrowthStage')
    Feeding = apps.get_model('feeding', 'Feeding')

    default_stage, _ = GrowthStage.objects.get_or_create(
        growth_code='GROWTH-AUTO',
        defaults={
            'growth_name': 'Auto GROWTH-AUTO',
            'date': timezone.now(),
        },
    )

    for feeding in Feeding.objects.select_related('batch_code__growth_stage').iterator():
        batch = getattr(feeding, 'batch_code', None)
        batch_growth = getattr(batch, 'growth_stage', None)
        Feeding.objects.filter(pk=feeding.pk).update(
            growth_stage=batch_growth or default_stage,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0002_add_repeat_days_to_feeding'),
        ('growth', '0002_alter_growthstage_growth_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeding',
            name='growth_stage',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='growth.growthstage',
            ),
        ),
        migrations.RunPython(set_default_growth_stage, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='feeding',
            name='growth_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growth.growthstage'),
        ),
    ]
