# Generated by Django 6.0.2 on 2026-02-23 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batch', '0004_alter_pigbatches_batch_code_and_more'),
        ('growth', '0002_alter_growthstage_growth_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_code', models.CharField(max_length=120, unique=True)),
                ('pig_age_days', models.IntegerField()),
                ('avg_weight', models.FloatField()),
                ('date', models.DateTimeField()),
                ('batch_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batch.pigbatches')),
                ('growth_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growth.growthstage')),
            ],
        ),
    ]
