# Generated by Django 6.0.4 on 2026-04-12 05:27

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0004_alter_pigbatches_batch_code_and_more'),
        ('growth', '0002_alter_growthstage_growth_code_and_more'),
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['date', 'record_code']},
        ),
        migrations.AddConstraint(
            model_name='record',
            constraint=models.UniqueConstraint(models.F('batch_code'), django.db.models.functions.datetime.TruncDate('date'), name='unique_record_batch_per_utc_day'),
        ),
    ]
