# Generated by Django 6.0.4 on 2026-04-12 05:27

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('record', '0002_alter_record_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='record',
            constraint=models.UniqueConstraint(
                models.F('batch_code'),
                django.db.models.functions.datetime.TruncDate('date'),
                name='unique_record_batch_per_utc_day',
            ),
        ),
    ]
